replace spaces with tabs in init.d/starcal

diff --git a/init.d/starcal b/init.d/starcal
--- a/init.d/starcal
+++ b/init.d/starcal
@@ -36,12 +36,12 @@ PID=/run/starcal-server.pid
 #
 do_start()
 {
-    # Return
-    #   0 if daemon has been started
-    #   1 if daemon was already running
-    #   2 if daemon could not be started
-    start-stop-daemon --start --quiet --pidfile $PID --startas /bin/bash -- -c "$START_CMD" --test > /dev/null || return 1
-    start-stop-daemon --start --quiet --pidfile $PID --startas /bin/bash -- -c "$START_CMD" || return 2
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PID --startas /bin/bash -- -c "$START_CMD" --test > /dev/null || return 1
+	start-stop-daemon --start --quiet --pidfile $PID --startas /bin/bash -- -c "$START_CMD" || return 2
 }
 
 #
@@ -49,75 +49,75 @@ do_start()
 #
 do_stop()
 {
-    # Return
-    #   0 if daemon has been stopped
-    #   1 if daemon was already stopped
-    #   2 if daemon could not be stopped
-    #   other if a failure occurred
-    start-stop-daemon --stop --quiet --retry=2 --pidfile $PID --name $NAME
-    RETVAL="$?"
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=2 --pidfile $PID --name $NAME
+	RETVAL="$?"
 
-    sleep 1
-    return "$RETVAL"
+	sleep 1
+	return "$RETVAL"
 }
 
 
 case "$1" in
-    start)
-        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-        do_start
-        case "$?" in
-            0)
-                [ "$VERBOSE" != no ] && log_end_msg 0
-                ;;
-            1)
-                [ "$VERBOSE" != no ] && log_end_msg 0
-                ;;
-            2)
-                [ "$VERBOSE" != no ] && log_end_msg 1
-                ;;
-        esac
-        ;;
-    stop)
-        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-        do_stop
-        case "$?" in
-            0)
-                [ "$VERBOSE" != no ] && log_end_msg 0
-                ;;
-            1)
-                [ "$VERBOSE" != no ] && log_end_msg 0
-                ;;
-            2)
-                [ "$VERBOSE" != no ] && log_end_msg 1
-                ;;
-        esac
-        ;;
-    restart)
-        log_daemon_msg "Restarting $DESC" "$NAME"
-        do_stop
-        case "$?" in
-            0|1)
-                do_start
-                case "$?" in
-                    0) log_end_msg 0 ;;
-                    1) log_end_msg 1 ;; # Old process is still running
-                    *) log_end_msg 1 ;; # Failed to start
-                esac
-                ;;
-            *)
-                # Failed to stop
-                log_end_msg 1
-                ;;
-        esac
-        ;;
-    status)
-        status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
-        ;;
-    *)
-        echo "Usage: $NAME {start|stop|restart|status}" >&2
-        exit 3
-        ;;
+	start)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+		do_start
+		case "$?" in
+			0)
+				[ "$VERBOSE" != no ] && log_end_msg 0
+				;;
+			1)
+				[ "$VERBOSE" != no ] && log_end_msg 0
+				;;
+			2)
+				[ "$VERBOSE" != no ] && log_end_msg 1
+				;;
+		esac
+		;;
+	stop)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+		do_stop
+		case "$?" in
+			0)
+				[ "$VERBOSE" != no ] && log_end_msg 0
+				;;
+			1)
+				[ "$VERBOSE" != no ] && log_end_msg 0
+				;;
+			2)
+				[ "$VERBOSE" != no ] && log_end_msg 1
+				;;
+		esac
+		;;
+	restart)
+		log_daemon_msg "Restarting $DESC" "$NAME"
+		do_stop
+		case "$?" in
+			0|1)
+				do_start
+				case "$?" in
+					0) log_end_msg 0 ;;
+					1) log_end_msg 1 ;; # Old process is still running
+					*) log_end_msg 1 ;; # Failed to start
+				esac
+				;;
+			*)
+				# Failed to stop
+				log_end_msg 1
+				;;
+		esac
+		;;
+	status)
+		status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
+		;;
+	*)
+		echo "Usage: $NAME {start|stop|restart|status}" >&2
+		exit 3
+		;;
 esac
 
 :
